- name: publish

  uses: action-runner/npm-publish

  with:

    tokens: |

      ${{ secrets.NPM_TOKEN }}

      ${{ secrets.GITHUB_TOKEN}}

    packageFiles: |

      package.json

    registries: |

      https://registry.npmjs.org/

      https://npm.pkg.github.com
      
      - name: npm-multiple-publish

  uses: action-runner/npm-publish@1.6.2
