- name: Upload files to a GitHub release (Termux's fork)

  # You may pin to the exact commit or the version.

  # uses: termux/upload-release-action@2d39746a6bdeb09ad9661e46f10e269f57a0f72f

  uses: termux/upload-release-action@v4.1.0

  with:

    # GitHub token.

    repo_token: 

    # Local file to upload.

    file: 

    # Tag to use as a release.

    tag: 

    # Name of the asset. When not provided will use the file name. Unused if file_glob is set to "true".

    asset_name: # optional

    # Overwrite the release in case it already exists.

    overwrite: # optional

    # If true the file can be a glob pattern, asset_name is ignored if this is true.

    file_glob: # optional

    # If set to true, upload-release-action will skip if file_glob does not match any files. Ignored if file_glob is not set

    skip_if_no_glob_match: # optional

    # Mark the release as a pre-release. Defaults to "false".

    prerelease: # optional

    # Explicitly set a release name. Defaults to empty which will cause the release to take the tag as name on GitHub.

    release_name: # optional

    # Content of the release text. Empty by default.

    body: # optional

    # Specify the name of the GitHub repository in which the GitHub release will be created, edited, and deleted. If the repository is other than the current, it is required to create a personal access token with `repo`, `user`, `admin:repo_hook` scopes to the foreign repository and add it as a secret. Defaults to the current repository

    repo_name: # optional

    # List of cryptographic checksums to calculate

    checksums: # optional
